version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: soulsforge-postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sf-user
      POSTGRES_PASSWORD: sf-password
      POSTGRES_DB: soulsforge-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: